# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#User.create!(email: 'mverapino@gmail.com', password:'alejandro5', encrypted_password: '$2a$10$2K37CPgC5zKCdTDzFwbVDOBXdNt2wAgIWVVOKBJX219Giivq0jSqm', name: 'Mauricio Vera') #.confirm!
#User.create!(email: 'testing@gmail.com',password:'testing1', encrypted_password: '$2a$10$WzjBLRDsxnpMYmM.iDFpJ.iA/Uf6LxqKc2XbclaKu7jYurwjd4WWy', name: 'Test') #.confirm!
Prediction.create!(question_type:1 , question:'¿Quién será el campeón?')
Prediction.create!(question_type:1 , question:'¿Quién será el sub-campeón?')
Prediction.create!(question_type:1 , question:'¿Quién será el tercero?')
Prediction.create!(question_type:2 , question:'¿Quién será el goleador?')
Prediction.create!(question_type:2 , question:'¿Quién será el mejor jugador?')
Prediction.create!(question_type:3 , question:'¿Cual será el resultado de Chile?')
Prediction.create!(question_type:4 , group:'A' , question:'¿Quién será el ganador del grupo A?')
Prediction.create!(question_type:4 , group:'A' , question:'¿Quién será el segundo del grupo A?')
Prediction.create!(question_type:4 , group:'B' , question:'¿Quién será el ganador del grupo B?')
Prediction.create!(question_type:4 , group:'B' , question:'¿Quién será el segundo del grupo B?')
Prediction.create!(question_type:4 , group:'C' , question:'¿Quién será el ganador del grupo C?')
Prediction.create!(question_type:4 , group:'C' , question:'¿Quién será el segundo del grupo C?')
Prediction.create!(question_type:4 , group:'D' , question:'¿Quién será el ganador del grupo D?')
Prediction.create!(question_type:4 , group:'D' , question:'¿Quién será el segundo del grupo D?')
Prediction.create!(question_type:4 , group:'E' , question:'¿Quién será el ganador del grupo E?')
Prediction.create!(question_type:4 , group:'E' , question:'¿Quién será el segundo del grupo E?')
Prediction.create!(question_type:4 , group:'F' , question:'¿Quién será el ganador del grupo F?')
Prediction.create!(question_type:4 , group:'F' , question:'¿Quién será el segundo del grupo F?')
Prediction.create!(question_type:4 , group:'G' , question:'¿Quién será el ganador del grupo G?')
Prediction.create!(question_type:4 , group:'G' , question:'¿Quién será el segundo del grupo G?')
Prediction.create!(question_type:4 , group:'H' , question:'¿Quién será el ganador del grupo H?')
Prediction.create!(question_type:4 , group:'H' , question:'¿Quién será el segundo del grupo H?')


Team.create!(group:'A' ,name: 'Brazil',)
Team.create!(group:'A' ,name: 'Croacia')
Team.create!(group:'A' ,name: 'Mexico')
Team.create!(group:'A' ,name: 'Camerun')
Team.create!(group:'B' ,name: 'España')
Team.create!(group:'B' ,name: 'Holanda')
Team.create!(group:'B' ,name: 'Chile')
Team.create!(group:'B' ,name: 'Australia')
Team.create!(group:'C' ,name: 'Colombia')
Team.create!(group:'C' ,name: 'Grecia')
Team.create!(group:'C' ,name: 'Costa de Marfil')
Team.create!(group:'C' ,name: 'Japon')
Team.create!(group:'D' ,name: 'Uruguay')
Team.create!(group:'D' ,name: 'Italia')
Team.create!(group:'D' ,name: 'Inglaterra')
Team.create!(group:'D' ,name: 'Costa Rica')
Team.create!(group:'E' ,name: 'Suiza')
Team.create!(group:'E' ,name: 'Francia')
Team.create!(group:'E' ,name: 'Ecuador')
Team.create!(group:'E' ,name: 'Honduras')
Team.create!(group:'F' ,name: 'Argentina')
Team.create!(group:'F' ,name: 'Bosnia')
Team.create!(group:'F' ,name: 'Nigeria')
Team.create!(group:'F' ,name: 'Iran')
Team.create!(group:'G' ,name: 'Alemania')
Team.create!(group:'G' ,name: 'USA')
Team.create!(group:'G' ,name: 'Portugal')
Team.create!(group:'G' ,name: 'Ghana')
Team.create!(group:'H' ,name: 'Belgica')
Team.create!(group:'H' ,name: 'Rusia')
Team.create!(group:'H' ,name: 'Algeria')
Team.create!(group:'H' ,name: 'Korea del Sur')

Match.create!(local: Team.find_by(name:'Brazil'), visit:Team.find_by(name:'Croacia'),         time:DateTime.new(2014,6,12,17))
Match.create!(local: Team.find_by(name:'Mexico'), visit:Team.find_by(name:'Camerun'),         time:DateTime.new(2014,6,13,13))
Match.create!(local: Team.find_by(name:'España'), visit:Team.find_by(name:'Holanda'),         time:DateTime.new(2014,6,13,16))
Match.create!(local: Team.find_by(name:'Chile'), visit:Team.find_by(name:'Australia'),        time:DateTime.new(2014,6,13,18))
Match.create!(local: Team.find_by(name:'Colombia'), visit:Team.find_by(name:'Grecia'),        time:DateTime.new(2014,6,14,13))
Match.create!(local: Team.find_by(name:'Uruguay'), visit:Team.find_by(name:'Costa Rica'),     time:DateTime.new(2014,6,14,16))
Match.create!(local: Team.find_by(name:'Inglaterra'), visit:Team.find_by(name:'Italia'),      time:DateTime.new(2014,6,14,18))
Match.create!(local: Team.find_by(name:'Costa de Marfil'), visit:Team.find_by(name:'Japon'),  time:DateTime.new(2014,6,14,22))
Match.create!(local: Team.find_by(name:'Suiza'), visit:Team.find_by(name:'Ecuador'),          time:DateTime.new(2014,6,15,13))
Match.create!(local: Team.find_by(name:'Francia'), visit:Team.find_by(name:'Honduras'),       time:DateTime.new(2014,6,15,16))
Match.create!(local: Team.find_by(name:'Argentina'), visit:Team.find_by(name:'Bosnia'),       time:DateTime.new(2014,6,15,19))


User.create!(email: 'mverapino@gmail.com', password:'qwertyuiop', name: 'Mauricio Vera') #.confirm!
User.create!(email: 'testing@gmail.com',password:'testing1', name: 'Test') #.confirm!